
export const LOAD_INGREDIENTS = 'LOAD_INGREDIENTS';
export const LOAD_INGREDIENTS_SUCCESS = 'LOAD_INGREDIENTS_SUCCESS';
export const LOAD_INGREDIENTS_FAILED = 'LOAD_INGREDIENTS_FAILED';

export const MAKE_ORDER = 'MAKE_ORDER';
export const MAKE_ORDER_SUCCESS = 'MAKE_ORDER_SUCCESS';
export const MAKE_ORDER_FAILED  = 'MAKE_ORDER_FAILED';

export const SET_CURRENT_INGREDIENT = 'SET_CURRENT_INGREDIENT';
