export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR  = 'REGISTER_ERROR';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR  = 'LOGIN_ERROR';

export const PROFILE_REQUEST = 'PROFILE_REQUEST';
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
export const PROFILE_ERROR  = 'PROFILE_ERROR';

export const FORGOT_PASS_REQUEST = 'FORGOT_PASS_REQUEST';
export const FORGOT_PASS_ERROR  = 'FORGOT_PASS_ERROR';
export const FORGOT_PASS_SUCCESS = 'FORGOT_PASS_SUCCESS';

export const CLEAR_FORGOT_PASS_SUCCESS = 'RESET_FORGOT_PASS_SUCCESS';

export const RESET_PASS_REQUEST = 'RESET_PASS_REQUEST';
export const RESET_PASS_SUCCESS = 'RESET_PASS_SUCCESS';
export const RESET_PASS_ERROR  = 'RESET_PASS_ERROR';

export const CLEAR_RESET_PASS_SUCCESS = 'RESET_FORGOT_PASS_SUCCESS';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR  = 'LOGOUT_ERROR';


