export const MAKE_ORDER_REQUEST = 'MAKE_ORDER_REQUEST';
export const MAKE_ORDER_SUCCESS = 'MAKE_ORDER_SUCCESS';
export const MAKE_ORDER_ERROR  = 'MAKE_ORDER_ERROR';
export const ERASE_ORDER = 'ERASE_ORDER';

export const SET_ORDER_INGREDIENT  = 'SET_ORDER_INGREDIENT';
export const REMOVE_ORDER_INGREDIENT  = 'REMOVE_ORDER_INGREDIENT';
