export const MAKE_ORDER = 'MAKE_ORDER';
export const MAKE_ORDER_SUCCESS = 'MAKE_ORDER_SUCCESS';
export const MAKE_ORDER_FAILED  = 'MAKE_ORDER_FAILED';
export const ERASE_ORDER = 'ERASE_ORDER';

export const SET_ORDER_INGREDIENTS  = 'SET_ORDER_INGREDIENTS';
export const SET_ORDER_INGREDIENT  = 'SET_ORDER_INGREDIENT';
export const REMOVE_ORDER_INGREDIENT  = 'REMOVE_ORDER_INGREDIENT';

export const UPDATE_ORDER = 'UPDATE_ORDER';
