export const MAKE_ORDER = 'MAKE_ORDER';
export const MAKE_ORDER_SUCCESS = 'MAKE_ORDER_SUCCESS';
export const MAKE_ORDER_FAILED  = 'MAKE_ORDER_FAILED';

export const SET_ORDER_INGREDIENTS  = 'SET_ORDER_INGREDIENTS';
export const SET_ORDER_INGREDIENT  = 'SET_ORDER_INGREDIENT';
