export const SET_ORDER_INGREDIENT: 'SET_ORDER_INGREDIENT'  = 'SET_ORDER_INGREDIENT';
export const REMOVE_ORDER_INGREDIENT: 'REMOVE_ORDER_INGREDIENT'  = 'REMOVE_ORDER_INGREDIENT';
export const UPDATE_INGREDIENTS_ORDER: 'UPDATE_INGREDIENTS_ORDER' = 'UPDATE_INGREDIENTS_ORDER';
export const ERASE_INGREDIENTS_ORDER: 'ERASE_INGREDIENTS_ORDER' = 'ERASE_INGREDIENTS_ORDER';
