export const FETCH_ORDERS: 'FETCH_ORDERS' = 'FETCH_ORDERS';
export const CLEAR_ORDERS: 'CLEAR_ORDERS' = 'CLEAR_ORDERS';
export const NEW_ORDERS_ARRIVE: 'NEW_ORDERS_ARRIVE' = 'NEW_ORDERS_ARRIVE';
export const UPDATE_ORDERS_TOTALS: 'UPDATE_ORDERS_TOTALS' = 'UPDATE_ORDERS_TOTALS';
