export const FETCH_ORDERS: 'FETCH_ORDERS' = 'FETCH_ORDERS';
export const CLEAR_ORDERS: 'CLEAR_ORDERS' = 'CLEAR_ORDERS';
export const NEW_ORDERS_ARRIVE: 'NEW_ORDERS_ARRIVE' = 'NEW_ORDERS_ARRIVE';
export const LOAD_INGREDIENTS: 'LOAD_INGREDIENTS' = 'LOAD_INGREDIENTS';
