export const LOAD_ORDER_FROM_SERVER : 'LOAD_ORDER_FROM_SERVER' = 'LOAD_ORDER_FROM_SERVER';
export const LOAD_ORDER_FROM_SERVER_SUCCESS : 'LOAD_ORDER_FROM_SERVER_SUCCESS' = 'LOAD_ORDER_FROM_SERVER_SUCCESS';
export const SET_ORDER_LOCAL: 'SET_ORDER_LOCAL' = 'SET_ORDER_LOCAL';
